// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CZERTAINLY/CBOM-lens/internal/dscvr (interfaces: SupervisorContract)
//
// Generated by this command:
//
//	mockgen -destination=./mock/supervisor.go -package=mock github.com/CZERTAINLY/CBOM-lens/internal/dscvr SupervisorContract
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/CZERTAINLY/CBOM-lens/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSupervisorContract is a mock of SupervisorContract interface.
type MockSupervisorContract struct {
	ctrl     *gomock.Controller
	recorder *MockSupervisorContractMockRecorder
	isgomock struct{}
}

// MockSupervisorContractMockRecorder is the mock recorder for MockSupervisorContract.
type MockSupervisorContractMockRecorder struct {
	mock *MockSupervisorContract
}

// NewMockSupervisorContract creates a new mock instance.
func NewMockSupervisorContract(ctrl *gomock.Controller) *MockSupervisorContract {
	mock := &MockSupervisorContract{ctrl: ctrl}
	mock.recorder = &MockSupervisorContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupervisorContract) EXPECT() *MockSupervisorContractMockRecorder {
	return m.recorder
}

// ConfigureJob mocks base method.
func (m *MockSupervisorContract) ConfigureJob(ctx context.Context, name string, cfg model.Scan) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureJob", ctx, name, cfg)
}

// ConfigureJob indicates an expected call of ConfigureJob.
func (mr *MockSupervisorContractMockRecorder) ConfigureJob(ctx, name, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureJob", reflect.TypeOf((*MockSupervisorContract)(nil).ConfigureJob), ctx, name, cfg)
}

// JobConfiguration mocks base method.
func (m *MockSupervisorContract) JobConfiguration(ctx context.Context, name string) (model.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobConfiguration", ctx, name)
	ret0, _ := ret[0].(model.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobConfiguration indicates an expected call of JobConfiguration.
func (mr *MockSupervisorContractMockRecorder) JobConfiguration(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobConfiguration", reflect.TypeOf((*MockSupervisorContract)(nil).JobConfiguration), ctx, name)
}

// Start mocks base method.
func (m *MockSupervisorContract) Start(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", name)
}

// Start indicates an expected call of Start.
func (mr *MockSupervisorContractMockRecorder) Start(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSupervisorContract)(nil).Start), name)
}
